'use client';
import {useEffect,useState} from 'react';
import {money} from '@/lib/catalog';
import type {DashboardFilter} from '@/lib/store-dashboard';
import './store-dashboard.css';

type Ranked={id:string;name:string;presentation:string;quantity:number;amountCents:number};
type Summary={period:{from:string;to:string};pending:{intakePending:number;materialsPending:number;deliveryPending:number;overdue:number};totals:{approvedOrders:number;approvedAmountCents:number};statuses:{status:string;count:number}[];products:Ranked[];plans:Ranked[]};
type SummaryResponse = Summary & {error?:string};
const cards:{key:keyof Summary['pending'];filter:DashboardFilter;label:string}[]=[{key:'intakePending',filter:'intake_pending',label:'Fichas por revisar'},{key:'materialsPending',filter:'materials_pending',label:'Planes sin materiales'},{key:'deliveryPending',filter:'delivery_pending',label:'Pedidos por entregar'},{key:'overdue',filter:'overdue',label:'Fechas vencidas'}];
function today(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Mexico_City',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());return ['year','month','day'].map(k=>parts.find(p=>p.type===k)!.value).join('-');}
function initialRange(){const to=today();const date=new Date(`${to}T12:00:00Z`);date.setUTCDate(date.getUTCDate()-29);return{from:date.toISOString().slice(0,10),to};}
function RankedList({title,items}:{title:string;items:Ranked[]}){return <section className="sales-ranking"><h5>{title}</h5>{items.length?<ul>{items.map(item=><li key={item.id}><span><strong>{item.name}</strong><small>{item.presentation}</small></span><span>{item.quantity} {item.quantity===1?'unidad':'unidades'}<small>{money(item.amountCents/100)} MXN</small></span></li>)}</ul>:<p className="member-help">Sin ventas aprobadas en este periodo.</p>}</section>;}
export default function StoreDashboard({filter,onFilter,onAccessLost,refreshKey=0}:{filter:DashboardFilter;onFilter:(value:DashboardFilter)=>void;onAccessLost:()=>void;refreshKey?:number}){
 const [range,setRange]=useState(initialRange);const[draft,setDraft]=useState(initialRange);const[data,setData]=useState<Summary|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();async function load(){setLoading(true);setError('');try{const response=await fetch(`/api/store/admin/summary?from=${range.from}&to=${range.to}`,{credentials:'same-origin',cache:'no-store',signal:controller.signal});const json=await response.json() as SummaryResponse;if(controller.signal.aborted)return;if(response.status===401||response.status===403){setData(null);onAccessLost();return;}if(!response.ok)throw new Error(json.error||'No pudimos cargar el resumen.');setData(json);}catch(cause){if(!controller.signal.aborted)setError(cause instanceof Error?cause.message:'No pudimos cargar el resumen.');}finally{if(!controller.signal.aborted)setLoading(false);}}void load();return()=>controller.abort();},[range,refreshKey,onAccessLost]);
 return <section className="store-dashboard" aria-label="Resumen de la tienda"><h5>Lo que necesita tu atención</h5><p className="member-help">Pendientes de todos los pedidos aprobados. Selecciona una categoría para revisarlos.</p>{data&&<div className="pending-grid">{cards.map(card=><button type="button" key={card.key} aria-pressed={filter===card.filter} onClick={()=>onFilter(filter===card.filter?'all':card.filter)}><strong>{data.pending[card.key]}</strong><span>{card.label}</span></button>)}</div>}{error&&<p className="member-feedback error" role="alert">{error}</p>}<details className="sales-panel"><summary>Ventas y productos más pedidos</summary><form className="member-form sales-range" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);setRange({from:String(form.get('from')),to:String(form.get('to'))});}}><div><label htmlFor="sales-from">Desde</label><input id="sales-from" name="from" type="date" required min="2023-01-01" max={draft.to} value={draft.from} onChange={e=>setDraft(v=>({...v,from:e.target.value}))}/></div><div><label htmlFor="sales-to">Hasta</label><input id="sales-to" name="to" type="date" required min={draft.from} max={today()} value={draft.to} onChange={e=>setDraft(v=>({...v,to:e.target.value}))}/></div><button className="button outline" disabled={loading}>Consultar</button></form><p className="member-help">Hasta un año por consulta · horario de Ciudad de México. Los pendientes de arriba abarcan todos los periodos.</p>{data&&<><div className="sales-totals"><div><small>Ventas aprobadas</small><strong>{money(data.totals.approvedAmountCents/100)} <span>MXN</span></strong></div><div><small>Pedidos aprobados</small><strong>{data.totals.approvedOrders}</strong></div></div><p className="store-caption">Periodo consultado: {data.period.from} al {data.period.to}. Importes antes de comisiones; excluyen pedidos pendientes, rechazados o reembolsados y envíos cotizados por separado. Las piezas incluidas en un plan no se cuentan como ventas adicionales de productos.</p><RankedList title="Productos más vendidos" items={data.products}/><RankedList title="Planes contratados" items={data.plans}/></> }</details>{loading&&<p className="member-help" role="status">Actualizando resumen…</p>}</section>;
}
