export type CatalogItem = { id: string; name: string; price: number; priceProvisional: boolean; kind: 'product' | 'plan'; description: string; presentation?: string; excludedFromPlans?: boolean; planNote?: string; productGroup?: string; variantLabel?: string; image?: string; tag?: string; features?: string[] };
export const dessertPackDescription='Un paquete inicial de 5 piezas en total, a elegir entre nuestros productos; puedes incluir hasta 1 pastel individual de zanahoria o cheesecake';
export const dessertPackPreparation='El tiempo de preparación se acuerda al comenzar el plan';
export const catalog: CatalogItem[] = [
 {id:'rutina-90',name:'Activa tu fuerza',price:1490,priceProvisional:false,kind:'plan',description:'Una ruta de entrenamiento para avanzar a tu ritmo.',features:['Rutina de entrenamiento de 90 días','Rutina de movilidad incluida','Adaptada a tu objetivo y experiencia','Atención en línea o presencial']},
 {id:'integral-90',name:'Tu balance completo',price:2490,priceProvisional:false,kind:'plan',description:'Entrenamiento y alimentación que trabajan juntos.',features:['Rutina de entrenamiento de 90 días','Rutina de movilidad incluida','Plan de alimentación personalizado','Opción de integrar tus postres favoritos','Atención en línea o presencial']},
 {id:'dulce-90',name:'El lado dulce del plan',price:2990,priceProvisional:false,kind:'plan',description:'Prueba nuestros productos y decide con Carly cuáles integrar a tu alimentación.',features:['Todo lo del plan Tu balance completo','Rutina de movilidad incluida',dessertPackDescription,dessertPackPreparation,'Postres adicionales se compran por separado']},
 {id:'mermelada',name:'Mermelada sin azúcar',price:129,priceProvisional:false,kind:'product',presentation:'300 g',description:'Un toque de sabor para acompañar tus desayunos y antojos. Presentación de 300 g; consulta los sabores disponibles.',image:'/images/strawberry-jam.png',tag:'PARA TUS MAÑANAS'},
 {id:'galletas',name:'Psy Cookie',price:59,priceProvisional:false,kind:'product',presentation:'1 pieza',description:'Galleta de chocolate con adaptógenos, de forma redonda y cubierta con semillas de cáñamo. Una pausa deliciosa para disfrutar por pieza.',image:'/images/psy-cookie.jpg',tag:'CHOCOLATE + CÁÑAMO'},
 {id:'core-cookie',name:'Core Cookie',price:55,priceProvisional:false,kind:'product',presentation:'1 pieza',description:'Galleta de vainilla con centro firme de chocolate, chispas de chocolate y nuez por encima. Texturas que se encuentran en cada mordida.',image:'/images/core-cookie.jpg',tag:'VAINILLA + CHOCOLATE'},
 {id:'golden-milk',name:'Golden milk',price:189,priceProvisional:false,kind:'product',presentation:'250 g',description:'Dale un momento cálido a tu día. Presentación de 250 g; consulta las indicaciones de preparación.',image:'/images/golden-milk.png',tag:'UN RITUAL DELICIOSO'},
 {id:'pastel-zanahoria',name:'Pastel de zanahoria',price:95,priceProvisional:false,kind:'product',presentation:'Individual · 1 porción',productGroup:'pastel-zanahoria',planNote:'Hasta 1 pastel individual dentro de las 5 piezas del plan con postres',variantLabel:'Individual · 1 porción',description:'Elaborado con harina de almendras y endulzado con alulosa, sin azúcar añadida. Con cubierta cremosa y nuez, en presentación individual.',image:'/images/carrot-cake.jpg',tag:'ALMENDRAS + ALULOSA'},
 {id:'pastel-zanahoria-grande',name:'Pastel de zanahoria',price:590,priceProvisional:false,kind:'product',presentation:'Grande · 15 cm de diámetro',productGroup:'pastel-zanahoria',excludedFromPlans:true,variantLabel:'Grande · 15 cm de diámetro',description:'Elaborado con harina de almendras y endulzado con alulosa, sin azúcar añadida. Con cubierta cremosa y nuez. Pastel completo de 15 cm de diámetro.',image:'/images/carrot-cake.jpg',tag:'ALMENDRAS + ALULOSA'},
 {id:'tiramisu',name:'Tiramisú saludable',price:109,priceProvisional:false,kind:'product',presentation:'Individual · 1 porción',description:'Nuestra versión saludable de este clásico, en una presentación individual para disfrutar a cucharadas.',image:'/images/tiramisu.jpg',tag:'TU MOMENTO DE POSTRE'},
 {id:'minitartaleta-pina-datil',name:'Minitartaleta Crumble de Piña y Dátil',price:65,priceProvisional:false,kind:'product',presentation:'1 pieza',description:'Minitartaleta redonda de piña y dátil, con cubierta crumble. Sabor frutal y una textura crujiente para tu pausa dulce.',image:'/images/pineapple-date-tartlets.jpg',tag:'PIÑA + DÁTIL'},
 {id:'cheesecake-carlyfit',name:'Cheesecake Carlyfit',price:99,priceProvisional:false,kind:'product',presentation:'Individual · 1 porción',productGroup:'cheesecake-carlyfit',planNote:'Hasta 1 pastel individual dentro de las 5 piezas del plan con postres',variantLabel:'Individual · 1 porción',description:'El cheesecake de la casa, con textura cremosa y una base crujiente. Una porción individual para disfrutar a tu ritmo.',image:'/images/carlyfit-cheesecake.jpg',tag:'EL CHEESECAKE DE LA CASA'},
 {id:'cheesecake-carlyfit-grande',name:'Cheesecake Carlyfit',price:590,priceProvisional:false,kind:'product',presentation:'Grande · 15 cm de diámetro',productGroup:'cheesecake-carlyfit',excludedFromPlans:true,variantLabel:'Grande · 15 cm de diámetro',description:'El cheesecake de la casa, con textura cremosa y una base crujiente. Pastel completo de 15 cm de diámetro para compartir.',image:'/images/carlyfit-cheesecake.jpg',tag:'EL CHEESECAKE DE LA CASA'},
];
export const money = (value:number) => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(value);
export const whatsapp = (message:string) => `https://wa.me/5214433580280?text=${encodeURIComponent(message)}`;
export type CartLine = { id: string; quantity: number };
export function validateCart(value:unknown): CartLine[] {
 if(!Array.isArray(value)||!value.length||value.length>catalog.length)throw new Error('Selecciona al menos un producto o plan.');
 const seen = new Set<string>();
 return value.map((row:unknown)=>{if(!row||typeof row!=='object')throw new Error('Carrito inválido.');const {id,quantity}=row as CartLine;if(typeof id!=='string'||!catalog.some(p=>p.id===id)||seen.has(id)||!Number.isInteger(quantity)||quantity<1||quantity>20)throw new Error('Producto o cantidad inválida.');seen.add(id);return {id,quantity};});
}
