import {validateCheesecakeTopping,type CheesecakeTopping} from './product-options';
export type CatalogItem = { id: string; name: string; price: number; priceProvisional: boolean; kind: 'product' | 'plan'; available?: boolean; description: string; presentation?: string; excludedFromPlans?: boolean; planNote?: string; productGroup?: string; variantLabel?: string; image?: string; tag?: string; features?: string[] };
export const dessertPackDescription='Un paquete inicial de 5 piezas en total, a elegir entre nuestros productos; puedes incluir hasta 1 pastel individual de zanahoria o cheesecake';
export const dessertPackPreparation='El tiempo de preparación se acuerda al comenzar el plan; los pasteles requieren 3 días de anticipación';
export const inPersonPlan: CatalogItem = {id:'presencial-mensual',available:false,name:'Entrena con Carly',price:2200,priceProvisional:false,kind:'plan',presentation:'1 mes · presencial',description:'Entrenamiento presencial en La Barca, Jalisco, adaptado a tus objetivos y a tu vida diaria.',features:['Rutina personalizada y movilidad','Video explicativo de tus rutinas','Horarios y fecha de inicio a acordar con Carly']};
export const catalog: CatalogItem[] = [
 {id:'rutina-90',name:'Activa tu fuerza',price:1490,priceProvisional:false,kind:'plan',presentation:'90 días · entrega única',description:'Una rutina que se adapta a tus tiempos, equipo y objetivos.',features:['Una sola entrega de tu rutina de 90 días','Para gimnasio o casa, según tus necesidades','Video explicativo de tus rutinas','Rutina de movilidad incluida','Seguimiento de tu avance y progresión','Modalidad a distancia']},
 {id:'integral-90',name:'Tu balance completo',price:2490,priceProvisional:false,kind:'plan',presentation:'90 días · entrega única',description:'Entrenamiento y alimentación adaptados a tu vida diaria.',features:['Una sola entrega de tu rutina de 90 días','Para gimnasio o casa, según tus necesidades','Video explicativo y rutina de movilidad','Plan de alimentación personalizado','Opción de integrar tus postres favoritos','Seguimiento de tu avance y progresión','Modalidad a distancia']},
 {id:'dulce-90',name:'El lado dulce del plan',price:2990,priceProvisional:false,kind:'plan',presentation:'90 días · entrega única',description:'Tu programa a distancia, con un paquete de postres para probar.',features:['Todo lo del plan Tu balance completo','Entrega única de rutina, video explicativo y movilidad','Seguimiento de tu avance y progresión',dessertPackDescription,dessertPackPreparation,'Postres adicionales se compran por separado']},
 inPersonPlan,
 {id:'mermelada',name:'Mermelada sin azúcar',price:129,priceProvisional:false,kind:'product',presentation:'300 g',description:'Un toque de sabor para acompañar tus desayunos y antojos. Presentación de 300 g; consulta los sabores disponibles.',image:'/images/strawberry-jam.png',tag:'PARA TUS MAÑANAS'},
 {id:'galletas',name:'Psi Cookie',price:59,priceProvisional:false,kind:'product',presentation:'1 pieza',description:'Galleta de chocolate con adaptógenos, de forma redonda y cubierta con semillas de cáñamo. Una pausa deliciosa para disfrutar por pieza.',image:'/images/psy-cookie.jpg',tag:'CHOCOLATE + CÁÑAMO'},
 {id:'core-cookie',name:'Core Cookie',price:55,priceProvisional:false,kind:'product',presentation:'1 pieza',description:'Galleta de vainilla con centro firme de chocolate, chispas de chocolate y nuez por encima. Texturas que se encuentran en cada mordida.',image:'/images/core-cookie.jpg',tag:'VAINILLA + CHOCOLATE'},
 {id:'golden-milk',name:'Golden milk',price:189,priceProvisional:false,kind:'product',presentation:'250 g',description:'Dale un momento cálido a tu día. Presentación de 250 g; consulta las indicaciones de preparación.',image:'/images/golden-milk.png',tag:'UN RITUAL DELICIOSO'},
 {id:'pastel-zanahoria',name:'Pastel de zanahoria',price:95,priceProvisional:false,kind:'product',presentation:'Individual · 1 porción',productGroup:'pastel-zanahoria',planNote:'Hasta 1 pastel individual dentro de las 5 piezas del plan con postres',variantLabel:'Individual · 1 porción',description:'Elaborado con harina de almendras y endulzado con alulosa, sin azúcar añadida. Con cubierta cremosa y nuez, en presentación individual.',image:'/images/carrot-cake.jpg',tag:'ALMENDRAS + ALULOSA'},
 {id:'pastel-zanahoria-grande',name:'Pastel de zanahoria',price:750,priceProvisional:false,kind:'product',presentation:'Grande · 15 cm de diámetro',productGroup:'pastel-zanahoria',excludedFromPlans:true,variantLabel:'Grande · 15 cm de diámetro',description:'Elaborado con harina de almendras y endulzado con alulosa, sin azúcar añadida. Con cubierta cremosa y nuez. Pastel completo de 15 cm de diámetro.',image:'/images/carrot-cake.jpg',tag:'ALMENDRAS + ALULOSA'},
 {id:'tiramisu',name:'Tiramisú saludable',price:140,priceProvisional:false,kind:'product',presentation:'Individual · 1 porción',description:'Nuestra versión saludable de este clásico, en una presentación individual para disfrutar a cucharadas.',image:'/images/tiramisu.jpg',tag:'TU MOMENTO DE POSTRE'},
 {id:'minitartaleta-pina-datil',name:'Minitartaleta Crumble de Piña y Dátil',price:95,priceProvisional:false,kind:'product',presentation:'1 pieza',description:'Minitartaleta redonda de piña y dátil, con cubierta crumble. Sabor frutal y una textura crujiente para tu pausa dulce.',image:'/images/pineapple-date-tartlets.jpg',tag:'PIÑA + DÁTIL'},
 {id:'cheesecake-carlyfit',name:'Cheesecake Carlyfit',price:99,priceProvisional:false,kind:'product',presentation:'Individual · 1 porción',productGroup:'cheesecake-carlyfit',planNote:'Hasta 1 pastel individual dentro de las 5 piezas del plan con postres',variantLabel:'Individual · 1 porción',description:'El cheesecake de la casa, con textura cremosa y una base crujiente. Una porción individual con mermelada a elegir: frutos rojos, manzana canela o fresa chía, endulzada con alulosa y sin recargo.',image:'/images/carlyfit-cheesecake.jpg',tag:'EL CHEESECAKE DE LA CASA'},
 {id:'cheesecake-carlyfit-grande',name:'Cheesecake Carlyfit',price:720,priceProvisional:false,kind:'product',presentation:'Grande · 15 cm de diámetro',productGroup:'cheesecake-carlyfit',excludedFromPlans:true,variantLabel:'Grande · 15 cm de diámetro',description:'El cheesecake de la casa, con textura cremosa y una base crujiente. Pastel completo de 15 cm de diámetro para compartir, con mermelada a elegir: frutos rojos, manzana canela o fresa chía, endulzada con alulosa y sin recargo.',image:'/images/carlyfit-cheesecake.jpg',tag:'EL CHEESECAKE DE LA CASA'},
];
export const money = (value:number) => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(value);
export const whatsapp = (message:string) => `https://wa.me/5214433580280?text=${encodeURIComponent(message)}`;
export type CartLine = { id: string; quantity: number; cheesecakeTopping?: CheesecakeTopping };
export function validateCart(value:unknown): CartLine[] {
 if(!Array.isArray(value)||!value.length||value.length>catalog.length)throw new Error('Selecciona al menos un producto o plan.');
 const seen = new Set<string>();
 return value.map((row:unknown)=>{if(!row||typeof row!=='object'||Array.isArray(row))throw new Error('Carrito inválido.');const {id,quantity,cheesecakeTopping:rawTopping}=row as CartLine;if(typeof id!=='string'||!catalog.some(p=>p.id===id)||seen.has(id)||!Number.isInteger(quantity)||quantity<1||quantity>20)throw new Error('Producto o cantidad inválida.');const cheesecakeTopping=validateCheesecakeTopping(id,rawTopping);seen.add(id);return {id,quantity,...(cheesecakeTopping?{cheesecakeTopping}:{})};});
}
